export const trans = {
  "authenticationTitle": "Konto | Maxilla",
  "createAccount": "Registreeru kasutajaks",
  "signupRentSpace": "rendi oma ruume",
  "login": "Logi sisse",
  "yourName": "Sinu nimi *",
  "namePlaceholder": "Ees- ja perekonnanimi",
  "email": "E-post *",
  "emailPlaceholder": "email@sinu.ee",
  "password": "Parool *",
  "retypePassword": "Sisesta parool uuesti *",
  "signup": "Registreeru",
  "oneSecond": "Moment…",
  "haveAccount": "Oled jube registreerunud? Logi sisse siin>>",
  "forgotPassword": "Parool on ununenud?",
  "dontHaveAccount": "Sul pole kontot?",
  "signupProvider": "Registreeru ja läheduses asuvad",
  "nearbyDoors": "ust on Sulle kohe avatavad!",
  "signupRentYourSpace": "Registreeru & rendi lihtsasti & turvaliselt oma ruume!",
  "nameError": "Palun, sisesta oma ees- ja perekonnanimi!",
  "wrongPass": "Sisestatud e-post ja/või parool on vale(d)!",
  "duplicateEmailError": "Sellise e-posti aadressiga kasutaja on juba registreeritud! Palun logi lihtsalt sisse või kui Sa ei mäleta oma parooli, siis vajuta 'Unustasid parooli?' nuppu all!",
  "passwordMissingError": "Palun vali tugev vähemalt 6 tähemärki parool, mis sisaldab vähemalt ühte suurt ja ühte väikest tähemärki!",
  "passwordMismatchError": "Sisestatud paroolid ei ühti!",
  "passwordStrengthError": "Sisestatud parool on liiga nõrk! Parool peab olema vähemalt 6 tähemärki pikk ja sisaldama vähemalt ühte suurt ja ühte väikest tähemärki!",
  "validEmailError": "Sisesta palun korrektne eksiteeriv emaili aadress!",
  "myAccount": "Minu konto",
  "postalAddress": "Postiaadress",
  "aboutMe": "Enda tutvustus",
  "language": "Keel",
  "discountOffers": "Saa sooduspakkumisi",
  "newPassword": "Uus parool",
  "newPasswordAgain": "Korda uut parooli",
  "changePassword": "Muuda oma parooli",
  "saveChanges": "Salvesta muudatused",
  "changeProfilePic": "Lae üles uus profiilipilt",
  "changePic": "Lae üles uus pilt",
  "mobileNumber": "Mobiili number",
  "displayMode": "Ekraani režiim",
  "darkMode": "Tume režiim",
  "lightMode": "Hele režiim",
  "profileSaved": "Profiil salvestatud!",
  "uploading": "Laen üles…",
  "OpenCamera": "Tee kaameraga uus pilt",
  "largerThan": "Faili suurus tohib olla maksimaalselt 15 MB!",
  "invalidImage": "Vigane pildifail!",
  "imageUploaded": "Profiilipilt uuendatud!",
  "aboutmePlaceholder": "Näiteks amet, hobid, üldse endast, mis tekitaks usaldust neis, kes Sulle oma ruume rendivad"
}